### PR TITLE
Update template rendering and update_attributes for Rails 6.1; adds Appraisals for Rails 6.0 and 6.1

### PR DESCRIPTION
**Pull request by bensheldon**
- Rails 6.1 removes `render file: ''` support for templates. This has been replaced with `prepend_view_path` to include template root. There is a pre-existing TODO to convert to an Engine, which would clean this all right up. 
- Rails 6.1 removes `ActiveRecord::Base#update_attributes`; replaced with `#update`
- Adds Appraisals for Rails 6.0 and 6.1

### CODE REVIEW

**Comment by frostmark** [comment]
Hey @phillbaker. Maybe I will fix the specs and we will merge that?

**Comment by phillbaker** [comment]
👋 I'm not actively working on this open source project any more. 

@assaf I'm not sure if you've given other folks contributor access to this repo, if not, let's maybe open an issue and ask for volunteers?

**Comment by frostmark** [comment]
That would be nice!

**Comment by bensheldon** [comment]
I have repository access, but not to release on Rubygems. I can pick this up again if no one else is quicker to overcome the challenges.

**Comment by bensheldon** [comment]
@frostmark that would be fantastic if you can get this passing in local development.

I opened up #369 to try to get CI running again on the project.

**Comment by phillbaker** [comment]
I do have access to add you on ruby gems, can your confirm your username
there?

**Comment by bensheldon** [comment]
Oops, I shouldn't have rebased this branch because I realized people have the old commit pinned 🤦  I just undid that so the original commit is in the branch.

**Comment by bensheldon** [comment]
Tests are green; I tried it on my own application. I guess it's ready 🚀

**Comment by frostmark** [comment]
That awesome!

**Comment by bensheldon** [comment]
I released this on rubygems in v3.0.1 too 🥳

**Pull request merged**
